export interface Project {
    id: string;
    title: string;
    description: string;
    category: string;
    year: number;
    technologies: string[];
    image?: string;
    viewUrl?: string;
    sourceUrl?: string;
}

export function getUniqueCategories(projects: Project[]): string[] {
    return Array.from(new Set(projects.map((p) => p.category))).sort();
}

export function getUniqueTechnologies(projects: Project[]): string[] {
    return Array.from(new Set(projects.flatMap((p) => p.technologies))).sort();
}

export function getUniqueYears(projects: Project[]): number[] {
    return Array.from(new Set(projects.map((p) => p.year))).sort((a, b) => b - a);
}

export const PROJECTS: Project[] = [
    {
        id: "1",
        title: "ProjectileHP",
        description: "PocketMine-MP plugin that show entity health on projectile hit with sound feedback.",
        category: "Plugin",
        year: 2019,
        technologies: ["PHP"],
        sourceUrl: "https://gitlab.com/yehezkieldio/projectilehp",
        viewUrl: "https://www.youtube.com/watch?v=NI9k6nBrmpU",
        image: "/img_projects/1.png",
    },
    {
        id: "2",
        title: "Lumine",
        description: "Multipurpose Discord bot providing utility features for Indonesian communities.",
        category: "Discord Bot",
        year: 2021,
        technologies: ["JavaScript", "discord.js"],
        sourceUrl: "https://gitlab.com/yehezkieldio/lumine",
    },
    {
        id: "3",
        title: "LokasiZero",
        description: "Fictional cybersecurity company landing page created for a web design competition.",
        category: "Web Application",
        year: 2023,
        technologies: ["HTML", "CSS", "JavaScript"],
        sourceUrl: "https://github.com/yehezkieldio/lokasi-zero",
        viewUrl: "https://yehezkieldio.github.io/lokasi-zero",
        image: "/img_projects/3.png",
    },
    {
        id: "4",
        title: "Aqua",
        description: "Product showcase landing page concept for AQUA mineral water brand.",
        category: "Web Application",
        year: 2022,
        technologies: ["HTML", "CSS", "JavaScript"],
        sourceUrl: "https://github.com/yehezkieldio/aqua-concept-website",
        viewUrl: "https://yehezkieldio.github.io/aqua-concept-website",
        image: "/img_projects/4.png",
    },
    {
        id: "5",
        title: "Raiden",
        description: "Operations and management Discord bot for the Genshin Impact ID community.",
        category: "Discord Bot",
        year: 2021,
        technologies: ["TypeScript", "discord.js"],
        sourceUrl: "https://gitlab.com/yehezkieldio/raiden",
    },
    {
        id: "6",
        title: "Mythcord",
        description: "Multipurpose Discord bot with feature-rich utilities and integrated web dashboard.",
        category: "Discord Bot",
        year: 2021,
        technologies: ["TypeScript", "discord.js", "React", "Next.js"],
        sourceUrl: "https://gitlab.com/yehezkieldio/mythcord",
    },
    {
        id: "7",
        title: "genshin-db",
        description: "Data package for providing Genshin Impact data on various in-game elements.",
        category: "Library",
        technologies: ["JavaScript"],
        year: 2020,
        sourceUrl: "https://github.com/theBowja/genshin-db",
        viewUrl: "https://www.npmjs.com/package/genshin-db",
    },
    {
        id: "8",
        title: "Finance Recap",
        description: "Web application for extracting and visualizing financial data from Excel spreadsheets.",
        category: "Web Application",
        year: 2022,
        technologies: ["PHP", "Laravel", "MongoDB"],
        sourceUrl: "https://github.com/astrantialabs/finance-recap",
        image: "/img_projects/8.png",
    },
    {
        id: "9",
        title: "Inventory Management",
        description: "Office asset inventory management system for organizational resource tracking.",
        category: "Web Application",
        year: 2022,
        technologies: ["React", "Next.js", "Nest.js", "MongoDB"],
        sourceUrl: "https://github.com/astrantialabs/administrare",
        image: "/img_projects/9.png",
    },
    {
        id: "10",
        title: "Pittacia",
        description: "CLI tool for managing GitHub issue labels from JSON configuration files.",
        category: "CLI",
        year: 2023,
        technologies: ["Rust"],
        sourceUrl: "https://github.com/yehezkieldio/pittacia",
    },
    {
        id: "11",
        title: "Voidsong",
        description: "Self-hosted API aggregator providing access to various random content sources.",
        category: "API",
        year: 2024,
        technologies: ["Rust", "Docker"],
        sourceUrl: "https://github.com/yehezkieldio/voidsong",
    },
    {
        id: "12",
        title: "Dikaios",
        description: "Desktop application providing comprehensive IP address management utilities.",
        category: "Desktop Application",
        year: 2024,
        technologies: ["Tauri", "Vite", "Rust", "React", "TypeScript"],
        sourceUrl: "https://github.com/yehezkieldio/dikaios",
        image: "/img_projects/12.png",
    },
    {
        id: "13",
        title: "TrashTrack",
        description: "IoT waste management system with filtering and real-time monitoring capabilities.",
        category: "Mobile Application",
        year: 2024,
        technologies: ["Capacitor", "Ionic", "Vite", "React", "TypeScript"],
        sourceUrl: "https://github.com/trashtrackteam/trashtrack",
        image: "/img_projects/13.png",
    },
    {
        id: "14",
        title: "Imperia",
        description: "Comprehensive multipurpose Discord bot for server management and utility tasks.",
        category: "Discord Bot",
        year: 2024,
        technologies: ["TypeScript", "discord.js", "PostgreSQL", "Dragonfly"],
        sourceUrl: "https://github.com/yehezkieldio/imperia-2024",
    },
    {
        id: "15",
        title: "Topaz",
        description: "Personal reading tracker for fanfiction, webnovels, and online fiction.",
        category: "Web Application",
        year: 2025,
        technologies: ["React", "Next.js", "TypeScript", "PostgreSQL"],
        sourceUrl: "https://github.com/yehezkieldio/topaz",
        viewUrl: "https://topaz-elizielx.vercel.app",
        image: "/img_projects/15.png",
    },
    {
        id: "16",
        title: "Firefly",
        description: "CLI tool for automated semantic versioning, changelog generation, and GitHub release.",
        category: "CLI",
        year: 2025,
        technologies: ["Bun", "TypeScript"],
        sourceUrl: "https://github.com/yehezkieldio/firefly",
        viewUrl: "https://npmjs.com/package/fireflyy",
    },
    {
        id: "17",
        title: "Sleeplesslabs",
        description: "Landing page for Sleeplesslabs software development group.",
        category: "Web Application",
        year: 2024,
        technologies: ["React", "Next.js", "TypeScript"],
        sourceUrl: "https://github.com/sleeplesslabs/sleeplesslabs-web",
        image: "/img_projects/17.png",
    },
    {
        id: "18",
        title: "Asteria",
        description: "Remote input relay for controlling Windows systems using Linux peripherals.",
        category: "CLI",
        year: 2025,
        technologies: ["Rust"],
        sourceUrl: "https://github.com/yehezkieldio/asteria",
    },
    {
        id: "19",
        title: "Kyra",
        description: "Data transfer tool between Windows and Arch Linux systems.",
        category: "CLI",
        year: 2025,
        technologies: ["Rust"],
        sourceUrl: "https://github.com/yehezkieldio/kyra",
    },
    {
        id: "20",
        title: "Astral",
        description: "Landing page template with a design inspired by GitBook and the stars.",
        category: "Web Application",
        year: 2024,
        technologies: ["Astro"],
        sourceUrl: "https://github.com/yehezkieldio/astral",
        image: "/img_projects/20.png",
    },
    {
        id: "21",
        title: "Callisto",
        description: "Automated setup and config tool for development environment initialization.",
        category: "CLI",
        year: 2024,
        technologies: ["TypeScript"],
        sourceUrl: "https://github.com/yehezkieldio/callisto",
    },
    {
        id: "22",
        title: "ArgoNavis",
        description: "Gemini-powered Discord bot with retrieval-augmented generation (RAG) capabilities.",
        category: "Discord Bot",
        year: 2025,
        technologies: ["TypeScript", "discord.js", "PostgreSQL"],
        sourceUrl: "https://github.com/yehezkieldio/argonavis",
    },
    {
        id: "23",
        title: "Amaya",
        description: "Schema-driven CLI for automated, opinionated development environment configuration.",
        category: "CLI",
        year: 2025,
        technologies: ["Rust"],
        sourceUrl: "https://github.com/yehezkieldio/amaya",
    },
    {
        id: "24",
        title: "Avalon",
        description: "Serverless Discord bot on Cloudflare Workers for AI-powered chat interactions.",
        category: "Discord Bot",
        year: 2025,
        technologies: ["TypeScript", "LangChain", "Cloudflare Workers"],
        sourceUrl: "https://github.com/yehezkieldio/avalon",
    },
    {
        id: "25",
        title: "Starrlight",
        description: "Generate curated Awesome Lists from your GitHub starred repositories.",
        category: "CLI",
        year: 2025,
        technologies: ["Rust"],
        sourceUrl: "https://github.com/yehezkieldio/starrlight",
    },
    {
        id: "26",
        title: "Magnus",
        description: "Turn-based chess game for two players.",
        category: "Desktop Application",
        year: 2024,
        technologies: ["Visual Basic .NET"],
        sourceUrl: "https://github.com/yehezkieldio/magnus",
        image: "/img_projects/26.png",
    },
    {
        id: "27",
        title: "Antimony",
        description: "API wrapper for LiveKit providing real-time video/audio room and token management.",
        category: "API",
        year: 2024,
        technologies: ["Go", "Docker"],
        sourceUrl: "https://github.com/yehezkieldio/antimony",
    },
    {
        id: "28",
        title: "Imperia AI",
        description: "Flexible Discord bot with multi-provider AI integration for chat interactions.",
        category: "Discord Bot",
        year: 2025,
        technologies: ["TypeScript", "discord.js", "AI SDK"],
        sourceUrl: "https://github.com/yehezkieldio/imperia-ai",
    },
    {
        id: "29",
        title: "TrackRunny",
        description: "Personal portfolio website for TrackRunny.",
        category: "Web Application",
        year: 2020,
        technologies: ["HTML", "CSS", "JavaScript"],
        sourceUrl: "https://github.com/TrackRunny/TrackRunny-Website",
        image: "/img_projects/29.png",
    },
    {
        id: "30",
        title: "Obama",
        description: "Landing page for Obama, a feature-rich multipurpose Discord bot.",
        category: "Web Application",
        year: 2020,
        technologies: ["HTML", "CSS", "JavaScript"],
        sourceUrl: "https://github.com/FutureDeveloperZ/web",
        image: "/img_projects/30.png",
    },
    {
        id: "31",
        title: "ExynosNetwork",
        description: "Landing page for ExynosNetwork skyblock Minecraft Bedrock Edition server.",
        category: "Web Application",
        year: 2020,
        technologies: ["HTML", "CSS", "JavaScript"],
        viewUrl: "https://codepen.io/elizielx/pen/QWGRjXV",
        image: "/img_projects/31.png",
    },
];
