name: Code Quality

on:
    push:
        branches:
            - master

jobs:
    lint:
        name: Lint
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Bun
              uses: oven-sh/setup-bun@v2
              with:
                  bun-version: canary

            - name: Cache dependencies
              id: cache
              uses: actions/cache@v4
              with:
                  path: ./node_modules
                  key: ${{ runner.os }}-bun-${{ hashFiles('./bun.lock', './bun.lockb') }}

            - name: Install Dependencies
              if: ${{ steps.cache.outputs.cache-hit != 'true' }}
              run: bun install --frozen-lockfile

            - name: Run Lint
              run: bun run lint
    typecheck:
        name: Typecheck
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Bun
              uses: oven-sh/setup-bun@v2
              with:
                  bun-version: canary

            - name: Cache dependencies
              id: cache
              uses: actions/cache@v4
              with:
                  path: ./node_modules
                  key: ${{ runner.os }}-bun-${{ hashFiles('./bun.lock', './bun.lockb') }}

            - name: Install Dependencies
              if: ${{ steps.cache.outputs.cache-hit != 'true' }}
              run: bun install --frozen-lockfile

            - name: Run Lint
              run: bun run typecheck
